export const mapData = [
  {
    "type": "DESIGN",
    "lat": -14.518,
    "lng": -108.6741,
    "user": "chekspir",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "FORUM",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DESIGN",
    "lat": 2.135,
    "lng": -22.4461,
    "user": "Sky_",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "REGISTRATION",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DEVELOPMENT",
    "lat": -24.354,
    "lng": -104.335,
    "user": "billsedison",
    "challenge": "NIST: Differential Privacy",
    "operation": "VIEW",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DEVELOPMENT",
    "lat": 26.688,
    "lng": 10.3397,
    "user": "billsedison",
    "challenge": "Thor PDU Mass Commissioning Meteor Javascript Code Challenge",
    "operation": "SUBMISSIONS",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "ALGORITHM",
    "lat": 3.247,
    "lng": -144.3191,
    "user": "abedavera",
    "challenge": "Thor PDU Mass Commissioning Meteor Javascript Code Challenge",
    "operation": "FORUM",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DEVELOPMENT",
    "lat": 9.007,
    "lng": -16.6727,
    "user": "dweinheimer",
    "challenge": "NIST: Differential Privacy",
    "operation": "REVIEW",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DEVELOPMENT",
    "lat": -18.636,
    "lng": -75.9194,
    "user": "chekspir",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "REGISTRATION",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DESIGN",
    "lat": -17.696,
    "lng": -8.1405,
    "user": "billsedison",
    "challenge": "Thor PDU Mass Commissioning Meteor Javascript Code Challenge",
    "operation": "VIEW",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DEVELOPMENT",
    "lat": 13.347,
    "lng": -6.345,
    "user": "Sky_",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "SRM",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "ALGORITHM",
    "lat": 18.371,
    "lng": -105.0924,
    "user": "dweinheimer",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "VIEW",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DESIGN",
    "lat": 7.637,
    "lng": 72.9669,
    "user": "Sky_",
    "challenge": "NIST: Differential Privacy",
    "operation": "REGISTRATION",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DESIGN",
    "lat": 8.519,
    "lng": 150.6418,
    "user": "Sky_",
    "challenge": "Thor PDU Mass Commissioning Meteor Javascript Code Challenge",
    "operation": "SRM",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DATA-SCIENCE",
    "lat": -17.983,
    "lng": 0.3861,
    "user": "billsedison",
    "challenge": "NIST: Differential Privacy",
    "operation": "REVIEW",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DEVELOPMENT",
    "lat": 19.437,
    "lng": 1.4433,
    "user": "abedavera",
    "challenge": "Thor PDU Mass Commissioning Meteor Javascript Code Challenge",
    "operation": "FORUM",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DATA-SCIENCE",
    "lat": 27.401,
    "lng": -76.8727,
    "user": "Sky_",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "REGISTRATION",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DATA-SCIENCE",
    "lat": -21.046,
    "lng": -124.7182,
    "user": "Sky_",
    "challenge": "NIST: Differential Privacy",
    "operation": "REVIEW",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DATA-SCIENCE",
    "lat": 6.41,
    "lng": 21.8313,
    "user": "Sky_",
    "challenge": "NIST: Differential Privacy",
    "operation": "SUBMISSIONS",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DATA-SCIENCE",
    "lat": 6.14,
    "lng": 84.1983,
    "user": "dweinheimer",
    "challenge": "NIST: Differential Privacy",
    "operation": "REGISTRATION",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "ALGORITHM",
    "lat": -18.93,
    "lng": 103.0576,
    "user": "abedavera",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "SRM",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DEVELOPMENT",
    "lat": -29.241,
    "lng": 23.7489,
    "user": "dweinheimer",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "REGISTRATION",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DESIGN",
    "lat": -21.25,
    "lng": -11.4484,
    "user": "dweinheimer",
    "challenge": "NIST: Differential Privacy",
    "operation": "SRM",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "ALGORITHM",
    "lat": 6.037,
    "lng": -129.178,
    "user": "billsedison",
    "challenge": "Thor PDU Mass Commissioning Meteor Javascript Code Challenge",
    "operation": "SRM",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "ALGORITHM",
    "lat": 5.672,
    "lng": -38.2425,
    "user": "billsedison",
    "challenge": "NIST: Differential Privacy",
    "operation": "SUBMISSIONS",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DATA-SCIENCE",
    "lat": 15.243,
    "lng": -0.1113,
    "user": "billsedison",
    "challenge": "NIST: Differential Privacy",
    "operation": "VIEW",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "ALGORITHM",
    "lat": -17.574,
    "lng": -121.5039,
    "user": "abedavera",
    "challenge": "NIST: Differential Privacy",
    "operation": "REGISTRATION",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DEVELOPMENT",
    "lat": 8.975,
    "lng": -1.9039,
    "user": "Sky_",
    "challenge": "NIST: Differential Privacy",
    "operation": "SRM",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DEVELOPMENT",
    "lat": 13.203,
    "lng": 56.2272,
    "user": "dweinheimer",
    "challenge": "Thor PDU Mass Commissioning Meteor Javascript Code Challenge",
    "operation": "REVIEW",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "ALGORITHM",
    "lat": -29.414,
    "lng": 29.2189,
    "user": "Sky_",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "FORUM",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DEVELOPMENT",
    "lat": 0.196,
    "lng": -127.5386,
    "user": "Sky_",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "SUBMISSIONS",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DESIGN",
    "lat": -29.882,
    "lng": 111.7202,
    "user": "Sky_",
    "challenge": "NIST: Differential Privacy",
    "operation": "SRM",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DESIGN",
    "lat": -0.123,
    "lng": 124.991,
    "user": "billsedison",
    "challenge": "Thor PDU Mass Commissioning Meteor Javascript Code Challenge",
    "operation": "REVIEW",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DATA-SCIENCE",
    "lat": 7.618,
    "lng": -55.8959,
    "user": "abedavera",
    "challenge": "NIST: Differential Privacy",
    "operation": "VIEW",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DESIGN",
    "lat": -5.083,
    "lng": -63.621,
    "user": "chekspir",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "FORUM",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DATA-SCIENCE",
    "lat": -32.818,
    "lng": -39.512,
    "user": "chekspir",
    "challenge": "NIST: Differential Privacy",
    "operation": "REVIEW",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DEVELOPMENT",
    "lat": 2.771,
    "lng": 35.7812,
    "user": "abedavera",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "REVIEW",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DATA-SCIENCE",
    "lat": 10.108,
    "lng": -148.0484,
    "user": "Sky_",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "REVIEW",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DESIGN",
    "lat": 22.667,
    "lng": -27.2559,
    "user": "dweinheimer",
    "challenge": "NIST: Differential Privacy",
    "operation": "SUBMISSIONS",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DATA-SCIENCE",
    "lat": -10.994,
    "lng": -14.7876,
    "user": "Sky_",
    "challenge": "Thor PDU Mass Commissioning Meteor Javascript Code Challenge",
    "operation": "VIEW",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "ALGORITHM",
    "lat": 22.544,
    "lng": -20.3415,
    "user": "Sky_",
    "challenge": "Thor PDU Mass Commissioning Meteor Javascript Code Challenge",
    "operation": "SUBMISSIONS",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "ALGORITHM",
    "lat": 28.875,
    "lng": 143.3623,
    "user": "billsedison",
    "challenge": "NIST: Differential Privacy",
    "operation": "VIEW",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DESIGN",
    "lat": -15.203,
    "lng": 82.0698,
    "user": "billsedison",
    "challenge": "NIST: Differential Privacy",
    "operation": "SRM",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DESIGN",
    "lat": 2.112,
    "lng": 57.6681,
    "user": "Sky_",
    "challenge": "Thor PDU Mass Commissioning Meteor Javascript Code Challenge",
    "operation": "VIEW",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "ALGORITHM",
    "lat": 32.286,
    "lng": 18.2495,
    "user": "Sky_",
    "challenge": "Thor PDU Mass Commissioning Meteor Javascript Code Challenge",
    "operation": "SRM",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "ALGORITHM",
    "lat": -10.865,
    "lng": 130.9416,
    "user": "Sky_",
    "challenge": "Thor PDU Mass Commissioning Meteor Javascript Code Challenge",
    "operation": "SUBMISSIONS",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "ALGORITHM",
    "lat": -26.088,
    "lng": -94.5162,
    "user": "billsedison",
    "challenge": "NIST: Differential Privacy",
    "operation": "REGISTRATION",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DEVELOPMENT",
    "lat": -19.249,
    "lng": -86.0106,
    "user": "dweinheimer",
    "challenge": "Thor PDU Mass Commissioning Meteor Javascript Code Challenge",
    "operation": "SUBMISSIONS",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "ALGORITHM",
    "lat": 20.199,
    "lng": 89.6989,
    "user": "Sky_",
    "challenge": "Thor PDU Mass Commissioning Meteor Javascript Code Challenge",
    "operation": "REVIEW",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DATA-SCIENCE",
    "lat": -22.742,
    "lng": 86.7491,
    "user": "abedavera",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "SRM",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DEVELOPMENT",
    "lat": 29.329,
    "lng": -98.9469,
    "user": "Sky_",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "SRM",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DEVELOPMENT",
    "lat": -2.999,
    "lng": 128.171,
    "user": "Sky_",
    "challenge": "NIST: Differential Privacy",
    "operation": "FORUM",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DESIGN",
    "lat": 29.73,
    "lng": -84.4373,
    "user": "Sky_",
    "challenge": "Thor PDU Mass Commissioning Meteor Javascript Code Challenge",
    "operation": "FORUM",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DATA-SCIENCE",
    "lat": -18.554,
    "lng": 117.2426,
    "user": "dweinheimer",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "REGISTRATION",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DATA-SCIENCE",
    "lat": 10.717,
    "lng": -113.562,
    "user": "Sky_",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "SUBMISSIONS",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DEVELOPMENT",
    "lat": 0.546,
    "lng": 77.1031,
    "user": "abedavera",
    "challenge": "NIST: Differential Privacy",
    "operation": "VIEW",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DEVELOPMENT",
    "lat": -20.017,
    "lng": -45.357,
    "user": "Sky_",
    "challenge": "NIST: Differential Privacy",
    "operation": "VIEW",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DEVELOPMENT",
    "lat": 27.623,
    "lng": 140.1691,
    "user": "billsedison",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "REGISTRATION",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DESIGN",
    "lat": -1.474,
    "lng": -90.2896,
    "user": "dweinheimer",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "SRM",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "ALGORITHM",
    "lat": 15.069,
    "lng": -64.3435,
    "user": "Sky_",
    "challenge": "NIST: Differential Privacy",
    "operation": "REGISTRATION",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DATA-SCIENCE",
    "lat": 25.944,
    "lng": -106.8783,
    "user": "dweinheimer",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "REVIEW",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DEVELOPMENT",
    "lat": -15.574,
    "lng": 115.0606,
    "user": "chekspir",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "VIEW",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DEVELOPMENT",
    "lat": -18.352,
    "lng": 136.055,
    "user": "dweinheimer",
    "challenge": "Thor PDU Mass Commissioning Meteor Javascript Code Challenge",
    "operation": "FORUM",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "ALGORITHM",
    "lat": -22.067,
    "lng": 96.7859,
    "user": "Sky_",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "VIEW",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "ALGORITHM",
    "lat": 22.825,
    "lng": 139.758,
    "user": "Sky_",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "VIEW",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DATA-SCIENCE",
    "lat": -28.517,
    "lng": 66.5319,
    "user": "Sky_",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "REGISTRATION",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DESIGN",
    "lat": 27.871,
    "lng": -43.4926,
    "user": "Sky_",
    "challenge": "Thor PDU Mass Commissioning Meteor Javascript Code Challenge",
    "operation": "REVIEW",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DEVELOPMENT",
    "lat": -21.464,
    "lng": 148.3512,
    "user": "chekspir",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "VIEW",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DATA-SCIENCE",
    "lat": -28.632,
    "lng": 110.7561,
    "user": "abedavera",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "REGISTRATION",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DEVELOPMENT",
    "lat": -28.851,
    "lng": 93.5788,
    "user": "billsedison",
    "challenge": "NIST: Differential Privacy",
    "operation": "REGISTRATION",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DATA-SCIENCE",
    "lat": -5.192,
    "lng": -67.5105,
    "user": "billsedison",
    "challenge": "Thor PDU Mass Commissioning Meteor Javascript Code Challenge",
    "operation": "SUBMISSIONS",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DATA-SCIENCE",
    "lat": 23.998,
    "lng": -89.9269,
    "user": "Sky_",
    "challenge": "NIST: Differential Privacy",
    "operation": "VIEW",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DESIGN",
    "lat": -14.297,
    "lng": 17.4664,
    "user": "chekspir",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "FORUM",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DESIGN",
    "lat": -6.913,
    "lng": -144.485,
    "user": "abedavera",
    "challenge": "NIST: Differential Privacy",
    "operation": "SUBMISSIONS",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DEVELOPMENT",
    "lat": 23.663,
    "lng": 2.0461,
    "user": "dweinheimer",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "SRM",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DATA-SCIENCE",
    "lat": -4.905,
    "lng": 84.4555,
    "user": "chekspir",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "VIEW",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DATA-SCIENCE",
    "lat": -13.738,
    "lng": 120.6885,
    "user": "chekspir",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "FORUM",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DESIGN",
    "lat": 20.96,
    "lng": -23.0146,
    "user": "Sky_",
    "challenge": "Thor PDU Mass Commissioning Meteor Javascript Code Challenge",
    "operation": "REVIEW",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "ALGORITHM",
    "lat": -34.036,
    "lng": 24.6009,
    "user": "Sky_",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "SUBMISSIONS",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DATA-SCIENCE",
    "lat": 30.627,
    "lng": 139.1846,
    "user": "dweinheimer",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "FORUM",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DESIGN",
    "lat": -15.211,
    "lng": -90.8713,
    "user": "chekspir",
    "challenge": "Thor PDU Mass Commissioning Meteor Javascript Code Challenge",
    "operation": "VIEW",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "ALGORITHM",
    "lat": 11.87,
    "lng": 135.8408,
    "user": "chekspir",
    "challenge": "Thor PDU Mass Commissioning Meteor Javascript Code Challenge",
    "operation": "SRM",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DESIGN",
    "lat": 4.222,
    "lng": -6.7594,
    "user": "dweinheimer",
    "challenge": "NIST: Differential Privacy",
    "operation": "VIEW",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "ALGORITHM",
    "lat": -0.238,
    "lng": -124.5747,
    "user": "chekspir",
    "challenge": "NIST: Differential Privacy",
    "operation": "FORUM",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DESIGN",
    "lat": -0.323,
    "lng": -131.2566,
    "user": "billsedison",
    "challenge": "NIST: Differential Privacy",
    "operation": "SUBMISSIONS",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DESIGN",
    "lat": 5.505,
    "lng": -93.1048,
    "user": "billsedison",
    "challenge": "Thor PDU Mass Commissioning Meteor Javascript Code Challenge",
    "operation": "SUBMISSIONS",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DEVELOPMENT",
    "lat": -3.883,
    "lng": -139.0059,
    "user": "abedavera",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "SRM",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DEVELOPMENT",
    "lat": -8.177,
    "lng": 34.9742,
    "user": "dweinheimer",
    "challenge": "Thor PDU Mass Commissioning Meteor Javascript Code Challenge",
    "operation": "SRM",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "ALGORITHM",
    "lat": 10.593,
    "lng": 5.904,
    "user": "abedavera",
    "challenge": "Thor PDU Mass Commissioning Meteor Javascript Code Challenge",
    "operation": "SUBMISSIONS",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DESIGN",
    "lat": 3.452,
    "lng": 132.8422,
    "user": "dweinheimer",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "VIEW",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DATA-SCIENCE",
    "lat": 12.801,
    "lng": 142.3648,
    "user": "abedavera",
    "challenge": "Thor PDU Mass Commissioning Meteor Javascript Code Challenge",
    "operation": "SUBMISSIONS",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "ALGORITHM",
    "lat": 30.465,
    "lng": 12.5129,
    "user": "chekspir",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "FORUM",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DATA-SCIENCE",
    "lat": 6.675,
    "lng": 124.4479,
    "user": "abedavera",
    "challenge": "NIST: Differential Privacy",
    "operation": "FORUM",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DEVELOPMENT",
    "lat": -4.39,
    "lng": 35.244,
    "user": "abedavera",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "SUBMISSIONS",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DESIGN",
    "lat": -14.527,
    "lng": 114.0967,
    "user": "abedavera",
    "challenge": "Thor PDU Mass Commissioning Meteor Javascript Code Challenge",
    "operation": "SUBMISSIONS",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DATA-SCIENCE",
    "lat": 16.913,
    "lng": -110.8224,
    "user": "abedavera",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "SRM",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DATA-SCIENCE",
    "lat": 11.617,
    "lng": -58.0125,
    "user": "Sky_",
    "challenge": "Thor PDU Mass Commissioning Meteor Javascript Code Challenge",
    "operation": "FORUM",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "ALGORITHM",
    "lat": -32.041,
    "lng": -140.4476,
    "user": "Sky_",
    "challenge": "NIST: Differential Privacy",
    "operation": "FORUM",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DESIGN",
    "lat": -15.946,
    "lng": 10.3543,
    "user": "billsedison",
    "challenge": "NIST: Differential Privacy",
    "operation": "SRM",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DESIGN",
    "lat": 29.696,
    "lng": -113.3104,
    "user": "dweinheimer",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "SRM",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DEVELOPMENT",
    "lat": 11.498,
    "lng": -31.2641,
    "user": "dweinheimer",
    "challenge": "NIST: Differential Privacy",
    "operation": "VIEW",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  },
  {
    "type": "DEVELOPMENT",
    "lat": 14.556,
    "lng": 146.4921,
    "user": "abedavera",
    "challenge": "FAST - Topcoder Website Redesign Concepts Challenge",
    "operation": "SUBMISSIONS",
    "avatar": "avatar.jpg",
    "date": "12:35am",
    "city": "New York, USA"
  }
];